### ISSUE TITLE
Website rebrand and port to Next.js

### ISSUE THREAD

**Issue by makandz** [makandz/MySpotify#18]
Planning on combining the functionality of newtunes.xyz and MySpotify into a single application. That means functionality from the legacy PHP application will need to be ported over to TypeScript. 

# Tasks
## Initial website port
- [ ] New homepage design and boilerplate
- [ ] Login support with Spotify
- [ ] Viewing top tracks (short, medium, long)
- [ ] Viewing top artists (short, medium, long)
- [ ] Viewing recents
- [ ] Settings page for account details and deleting

## History tracking
- [ ] Connect a new database solution
- [ ] Implement database functionality to track history
- [ ] Combine this functionality with the website UI to be viewed
- [ ] Transfer over existing data to the new website? (_to be determined if I want it to be done, not sure_)

More tasks TBD?

**Comment by nathdevcoder** [comment]
Hi there.
I'm willing to contribute.
